data_SNP500 = read.csv("C://Users/User/Desktop/^GSPC.csv")
data_JNJ = read.csv("C://Users/User/Desktop/JNJ.csv")
library(TSA)
require(xts)
convert_ts = function(data){
  res = xts(data$Adj.Close, order.by=as.POSIXct(data$Date))
  return(res)}
ts_data_SNP500 = convert_ts(data_SNP500)
ts_data_JNJ = convert_ts(data_JNJ)
#5.12
#(1)
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(ts_data_SNP500,type='l',ylab='Prescription')
acf(ts_data_SNP500)
#(2)
log_data_SNP500 = log(ts_data_SNP500)
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(log_data_SNP500,type='l',ylab='Prescription')
acf(log_data_SNP500)
#(3)
ratio1 = 
  diff(data_SNP500$Adj.Close)/data_SNP500$Adj.Close[1:length(data_SNP500$Adj.
                                                             Close)-1]
fractional = xts(ratio1, 
                 order.by=as.POSIXct(data_SNP500$Date[2:length(data_SNP500$Date)]))
win.graph(width=4.875, height=2.5,pointsize=8)
ratio2 = diff(log(data_SNP500$Adj.Close))
nature_log = xts(ratio2, 
                 order.by=as.POSIXct(data_SNP500$Date[2:length(data_SNP500$Date)]))
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(fractional,type='l',ylab='Prescription')
plot(nature_log,type='l',ylab='Prescription')
acf(fractional)
acf(nature_log)
par(mfrow=c(1,2))
qqnorm(fractional)
qqline(fractional)
qqnorm(nature_log)
qqline(nature_log)
par(mfrow=c(1,2))
hist(fractional)
hist(nature_log)
t.test(fractional)
t.test(nature_log)
nature_log = as.vector(nature_log)
fractional = as.vector(fractional)
plot(x=nature_log,y=fractional)
#5.15
#(1)
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(ts_data_JNJ,type='l',ylab='Prescription')
acf(ts_data_JNJ)
#(2)
par(mfrow=c(1,1))
BoxCox.ar(data_JNJ$Adj.Close,lambda = seq(-5,5,0.01))
#(3)
square_data_JNJ = (ts_data_JNJ)^2
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(square_data_JNJ,type='l',ylab='Prescription')
acf(square_data_JNJ)
#(4)
ratio = diff((ts_data_JNJ)^2)[2:length(diff((ts_data_JNJ)^2))]
win.graph(width=4.875, height=2.5,pointsize=8)
par(mfrow=c(1,2))
plot(ratio,type='l',ylab='Prescription')
acf(ratio)
par(mfrow=c(1,2))
hist(ratio)
qqnorm(ratio)
qqline(ratio)
t.test(ratio)